version: '3.5'
services:
  mongo:
    container_name: blackjack-mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - '27018:27018'
    command: mongod --port 27018
  redis:
    container_name: blackjack-redis
    image: redis
    ports:
      - '6379:6379'
  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
    - REDIS_HOSTS=local:redis:6379
    ports:
    - "8081:8081"
